name: Pre-commit

on:
  pull_request:

permissions:
  id-token: write  # Required by SonarSource/ci-github-actions/config-npm for private npm auth
  contents: read

jobs:
  pre-commit:
    name: pre-commit
    runs-on: sonar-xs
    steps:
      - uses: SonarSource/ci-github-actions/config-npm@983645f538ff01044b1e567adb23e6f527d8b52a # 1.8.9
      - uses: SonarSource/gh-action_pre-commit@ea734ef4ee748f680f3b4ac268c1ba90e245effc # 1.2.1
        with:
          extra-args: >
            --from-ref=origin/${{ github.event.pull_request.base.ref }}
            --to-ref=${{ github.event.pull_request.head.sha }}
