name: Pre-commit

on:
  pull_request:

permissions:
  id-token: write  # Required by SonarSource/ci-github-actions/config-npm for private npm auth
  contents: read

jobs:
  pre-commit:
    name: pre-commit
    runs-on: sonar-xs
    steps:
      - uses: SonarSource/ci-github-actions/config-npm@de29c54be07c772c6afc381db8ae4bfcbfe4df12 # 1.8.0
      - uses: SonarSource/gh-action_pre-commit@2ddc0c7fdabce0adfaaa4075a17690972ed9961a # 1.2.0
        with:
          extra-args: >
            --from-ref=origin/${{ github.event.pull_request.base.ref }}
            --to-ref=${{ github.event.pull_request.head.sha }}
