name: Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test-signing:
    runs-on: github-windows-latest-s
    name: Test signing
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Test
        shell: pwsh
        run: |
          Write-Host "Creating test artifact"
          Write-Host "Test signing"
          Write-Host "Verify signature"
